
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
logging:
  level:
    com.music.demo: debug
server:
  port: 30008
knife4j:
  enable: true
  setting:
    language: zh_cn


mypath: D:/data/test/